#!/usr/bin/perl -w
#eexpress
#chenfengyuan modify
#remove Net::DBus

use utf8;
use strict;
use WWW::Mechanize;
#use Net::DBus;
use 5.010;
use Encode;

$_=$ARGV[0];
s/^http:\/([a-z])/http:\/\/$1/;
chomp; s/\//%2F/g; s/:/%3A/g;
$_="http://www.flvcd.com/parse.php?flag=&format=high&kw=$_&sbt=%BF%AA%CA%BCGO%21";
chdir "$ENV{HOME}/movie";
#my $bus = Net::DBus->session->get_service('org.freedesktop.Notifications')->get_object('/org/freedesktop/Notifications','org.freedesktop.Notifications');
my $mech = WWW::Mechanize->new(agent=> 'Opera/9.80 (X11; Linux i686; U; en) Presto/2.6.30 Version/10.60');
$mech -> get($_);
if ($mech->success()) {
    #        print $mech->title()."==================\n";
    $_=$mech->content();
    m{\Qdocument.title = "\E([^"]+)"};
    # m{\Q<strong>当前解析视频：</strong>\E\s+(\S+)\s+\Q<strong>\E}s;
    # /当前解析视频.*/; $_=$&; s/^.*?strong>//; s/<strong.*//;
    # #print $_."==================\n";
    say encode 'utf-8',"\e[31m\e[1m".$1."\e[0m==================\n";
    # s;/;;g;
    # s/\s//g;
    my $dir=$1//'foo';
    warn "perl:cannot make directory $_:$!" unless mkdir $dir;
    warn "perl:cannot change directory to $_:$!"unless chdir   $dir;

    my @link=$mech->find_all_links(text_regex => qr/http:\/\/.*[0-9a-fA-F]*/,);
    my $size=@link;
    #$bus->Notify("fetch_flash", 0, "sunny", "共获取 $size 个地址。", $size, [], { }, -1);
    say encode 'utf-8',"fetch_flash:共获取 $size 个地址";
    # open(LINK,">link.log");print LINK map $_->url()."\n",@link;close LINK;
    #        print map "=> ".$_->url()."\n",@_;
    my $filename='0' x (log($size)/log(10)+1) ;
    foreach (@link) {
	my $add=$_->url();
	say encode('utf-8',$size."下载 => $add");
	print encode 'utf-8',"\e]2;down_flash-".($filename+1)."/$size\a";
	`wget -nc --user-agent='Opera/9.80 (X11; Linux i686; U; en) Presto/2.6.30 Version/10.60' '$add' -O '$filename.flv'`;
	++$filename;
    }
    chdir '..';
} else {
    #$bus->Notify("fetch_flash", 0, "error", '解析失败，无效地址？', ':(', [], { }, -1);
    say STDERR encode 'utf-8',"解析失败，无效地址？:(";
}
#======================
