#!/usr/bin/perl
#This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
#written by Fengyuan Chen.

use 5.012;
use warnings;
use WWW::Mechanize;
use Encode;
use utf8;
use Data::Dumper;

print "Content-type:text/html\n\n";

use constant UA => 'Opera/9.80 (X11; Linux i686; U; en) Presto/2.6.30 Version/10.60';
use constant VERSION => 1.1;

my $mech=WWW::Mechanize->new(agent=>UA,cookie_jar=>{file=>'/dev/shm/115_cookie',autosave=>1});


sub login{
    my $username=shift;
    my $passwd=shift;
    my $mech=shift;
    $mech->get('http://u.115.com/');
    $mech->form_id('lf');
    $mech->tick('login[time]','on');
    $mech->submit_form(
		       with_fields=>{
				     'login[account]'=>$username,
				     'login[passwd]'=>$passwd,
				     }
		      );

}
sub get_content{
    my $mech=shift;
    my $url=shift;
    $mech->get($url);
    if ($mech->success) {
	return $mech->content;
    }
    else{
	warn "get_content error:".$mech->status;
	return undef;
    }
}

my @web_urls=split '_',$ENV{QUERY_STRING};

for my $web_url (@web_urls) {
    #get real download urls
    my $web_content=get_content($mech,$web_url);
    unless($web_content=~m'115down@gmail.com'){
	say STDERR 'relogin...';
	&login('115_down','fn4=IplVhkmwtqvjh7dy',$mech);
	$web_content=get_content($mech,$web_url);
    }
    my ($file_name,$file_url);
    given($web_content){
	when(/(\Q网络繁忙时段，非登陆用户其它下载地址暂时关闭。\E)/){
	    say encode 'utf-8',$1;
	    next;
	}
	when(/(\Q提取码不存在或已过期。\E)/||/(\Q很抱歉，文件不存在。\E)/){
	    say encode 'utf-8',$1;
	    next;
	}
    }
    $web_content=~/^var file_name = '(.+)';/m && ($file_name = $1);
    $web_content=~m{(http://(?:\d+?\.)?bak\.[^"]+)} && ($file_url=$1);
    unless($file_name && $file_url){
	say "file_url:".($file_url//"none");
	say encode 'utf-8',"file_name:".($file_name//"none");
    	say $web_url;
    	exit 1;
    }
    #show the download url
    say encode 'utf-8',"$file_name\:\:\:$file_url";
    sleep 1;
}
