#!/usr/bin/perl
#This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
#written by Fengyuan Chen.
#cfy1990 at gmail dot com

use 5.010;
use stirct;
use warnings;
use WWW::Mechanize;
use Encode;
use utf8;
use Log::Log4perl qw(:easy);

Log::Log4perl->easy_init(
			 {
			  level => $DEBUG,
			  file => '>> /home/cfy/115_log'
			  }
			);


print "Content-type:text/html\n\n";

use constant UA => 'Opera/9.80 (X11; Linux i686; U; en) Presto/2.6.30 Version/10.60';
use constant VERSION => 1.1;

my $mech=WWW::Mechanize->new(agent=>UA,cookie_jar=>{file=>'/dev/shm/115_cookie',autosave=>1});


sub login{
    my $username=shift;
    my $passwd=shift;
    my $mech=shift;
    $mech->get('http://u.115.com/');
    $mech->form_id('lf');
    $mech->tick('login[time]','on');
    $mech->submit_form(
		       with_fields=>{
				     'login[account]'=>$username,
				     'login[passwd]'=>$passwd,
				     }
		      );

}
sub get_content{
    my $mech=shift;
    my $url=shift;
    $mech->get($url);
    if ($mech->success) {
	return $mech->content;
    }
    else{
	warn "get_content error:".$mech->status;
	return undef;
    }
}

DEBUG join " ",my @web_urls=split '_',$ENV{QUERY_STRING};

for my $web_url (@web_urls) {
    #get real download urls
    my $web_content=get_content($mech,$web_url);
    unless($web_content=~m'115down@gmail.com'){
	DEBUG 'relogin...';
	&login('115_down','fn4=IplVhkmwtqvjh7dy',$mech);
	$web_content=get_content($mech,$web_url);
    }
    my ($file_name,$file_url);
    given($web_content){
	when(m{\Qpickcode_error">\E([^<]+)\Q</div>\E}){
	    my $msg=encode 'utf-8',$1;
	    say $msg;
	    DEBUG $msg;
	}
	default{
	    $web_content=~m{\Q<div class="fl"><i class="file-type"></i>\E([^<]+)\Q</div>\E} && ($file_name = $1);
	    $web_content=~m{(http://(?:\d+?\.)?bak\.[^"]+)} && ($file_url=$1);
	    #show the download url
	    $file_name//='none';
	    $file_url//='none';
	    my $msg=encode 'utf-8',"$file_name\:\:\:$file_url";
	    say $msg;
	    DEBUG $msg;
	}
    }
    sleep 1;
}
