#!/usr/bin/perl
#This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
#written by Fengyuan Chen.
use warnings;
use File::Find;
use File::Basename qw/dirname/;
use File::Path qw/mkpath/;

if(@ARGV<3){
    print STDERR "$0 string src dst\n";
    exit 1;
}
my $debug=1;
my $string=shift;
(my $src=shift)=~s:/::;
(my $dst=shift)=~s:/::;
my @files;
find(\&wanted,$src);
sub wanted {
    if($File::Find::name=~/\.html?$/){
	push @files,$File::Find::name;
    }
}
for my $file (@files){
    (my $dst_file=$file)=~s{\Q$src\E}{\Q$dst\E};
    print "[$file][$dst_file]\n" if defined $debug;
    open my $in,'<',$file;
    unless(-e  dirname($dst_file)){
	mkpath dirname($dst_file);
    }
    open my $out,'>',$dst_file;
    print $out $string,<$in>;
}
