#!/usr/bin/perl
#This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
#written by Fengyuan Chen.
#jeova.sanctus.unus@gmail.com
#usage:weather_email [zone] data-file
#email_address url in data-file
use 5.010;
use strict;
use warnings;
use WWW::Mechanize;
use Encode;
use Mail::Sender;
use utf8;
my $sender = new Mail::Sender({
			       smtp => '127.0.0.1',
			       from => 'weather@gmail.com',
			      });
my $mech=new WWW::Mechanize agent=> 'Opera/9.80 (X11; Linux i686; U; en) Presto/2.6.30 Version/10.63';
my $zone=@ARGV>1?shift:0;
say 'reading file....';
my %urls;

while(<>){
    next if /^#/;
    say join " ",my ($to,$url)=split;
    unless(exists $urls{$url}){
	say "getting $url";
	$mech->get($url);
	$urls{$url}=$mech->text();
    }
    my $msg=$urls{$url};
    $msg=~s/首页.*$//;
    $msg=~s/.+?天气预报//;
    $msg=~s/\r//g;
    $msg=~s/(?=\d+月)/\n/g;
    my ($wea)=$msg=~/日\s+(\S+)\s+[-\d]/;
    say $wea;
    $sender->MailMsg(
		     {
		      'encoding' => "Quoted-printable",
		      charset=>'utf-8',
		      to => $to,
		      subject => (encode 'utf-8',$wea),
		      msg => encode('utf-8',$msg).gmtime(time+$zone*3600),
		      # debug=>'w.log',
		     });
    say 'sent';
}
